# This role is required, otherwise pods will not communicate with pods part of other nodes.
# Error: Forbidden!Configured service account doesn't have access. Service account may have been revoked.
#        endpoints "customers-service" is forbidden: User "system:serviceaccount:default:default"
#        cannot get resource "endpoints" in API group "" in the namespace "default"

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-admin
  resourceVersion: "310662"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/default-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default